#! /usr/bin/env python3
"""
Senior Data Scientist.: Dr. Eddy Giusepe Chirinos Isidro

Script analyzer.py
==================
Logic for analyzing vehicle license plates using the VLM model from
embedl (embedl/Cosmos-Reason2-2B-W4A16). Supports both images and videos
through a single interface.
"""

import logging
import time
from pathlib import Path

import torch

from app.config import settings
from app.core.model import EmbedlVLM
from app.core.prompts import (
    SYSTEM_PROMPT_IMAGE,
    SYSTEM_PROMPT_VIDEO,
    USER_PROMPT_IMAGE,
    USER_PROMPT_VIDEO,
)
from app.schemas.analysis import AnalysisResult, MediaType
from app.utils.memory import cleanup_memory

logger = logging.getLogger(__name__)


def _build_messages(
    media_path: Path,
    media_type: MediaType,
) -> list[dict]:
    """
    Builds the message structure in the expected format by the chat template
    of the Qwen3-VL model.
    """
    if media_type == MediaType.IMAGE:
        system_text = SYSTEM_PROMPT_IMAGE
        user_text = USER_PROMPT_IMAGE
        media_field = {"type": "image", "image": str(media_path)}
    else:
        system_text = SYSTEM_PROMPT_VIDEO
        user_text = USER_PROMPT_VIDEO
        media_field = {"type": "video", "video": str(media_path)}

    return [
        {
            "role": "system",
            "content": [{"type": "text", "text": system_text}],
        },
        {
            "role": "user",
            "content": [
                media_field,
                {"type": "text", "text": user_text},
            ],
        },
    ]


def _run_inference(messages: list[dict], media_type: MediaType) -> str:
    """
    Executes the inference on the VLM model and returns the generated text.
    """
    model = EmbedlVLM.get_model()
    processor = EmbedlVLM.get_processor()
    device = EmbedlVLM.get_device()

    template_kwargs: dict = {
        "tokenize": True,
        "add_generation_prompt": True,
        "return_dict": True,
        "return_tensors": "pt",
        "processor_kwargs": {"truncation": True},
    }

    if media_type == MediaType.VIDEO:
        template_kwargs["fps"] = settings.VIDEO_FPS

    inputs = processor.apply_chat_template(messages, **template_kwargs)
    inputs = inputs.to(device)

    with torch.inference_mode():
        generated_ids = model.generate(
            **inputs,
            max_new_tokens=settings.MAX_NEW_TOKENS,
            do_sample=False,
            repetition_penalty=settings.REPETITION_PENALTY,
        )

    generated_ids_trimmed = [
        out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs.input_ids, generated_ids, strict=False)
    ]

    output_text = processor.batch_decode(
        generated_ids_trimmed,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    )

    del inputs
    del generated_ids
    del generated_ids_trimmed

    return output_text[0].strip()


def analyze_media(
    media_path: Path,
    media_type: MediaType,
    original_filename: str,
) -> AnalysisResult:
    """
    Analyses an image or video of a vehicle license plate.

    Args:
        media_path: Path to the file on the disk.
        media_type: Type of media (image or video).
        original_filename: Original filename of the file sent.

    Returns:
        AnalysisResult with the description generated by the model.

    Raises:
        torch.OutOfMemoryError: If the GPU runs out of memory.
        RuntimeError: If the model is not loaded.
    """
    if not EmbedlVLM.is_loaded():
        raise RuntimeError("VLM model has not been loaded.")

    logger.info(
        "Starting analysis: type=%s file=%s",
        media_type.value,
        original_filename,
    )

    start = time.perf_counter()

    try:
        messages = _build_messages(media_path, media_type)
        description = _run_inference(messages, media_type)
    finally:
        cleanup_memory()

    elapsed = time.perf_counter() - start

    logger.info(
        "Analysis completed in %.2fs: file=%s",
        elapsed,
        original_filename,
    )

    return AnalysisResult(
        description=description,
        media_type=media_type,
        filename=original_filename,
        processing_time_seconds=round(elapsed, 2),
    )
