#! /usr/bin/env python3
"""
Senior Data Scientist.: Dr. Eddy Giusepe Chirinos Isidro

Script schemas.py
=================
Pydantic models for requests and responses of the license
plate analysis API.
"""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field


class MediaType(StrEnum):
    """Type of media sent."""

    IMAGE = "image"
    VIDEO = "video"


class JobStatus(StrEnum):
    """Possible states of an analysis job."""

    QUEUED = "queued"  # Job is waiting in the queue to be processed.
    PROCESSING = "processing"  # Job is being processed.
    COMPLETED = "completed"  # Job is completed successfully.
    FAILED = "failed"  # Job failed to complete.


class AnalysisResult(BaseModel):
    """Result of the analysis of the license plate."""

    description: str = Field(
        ...,
        description="Complete description generated by the VLM model in English.",
    )
    media_type: MediaType = Field(..., description="Type of media analyzed.")
    filename: str = Field(..., description="Original filename of the file sent.")
    processing_time_seconds: float = Field(
        ...,
        ge=0,
        description="Total processing time in seconds.",
    )


class JobCreatedResponse(BaseModel):
    """Response returned immediately after creating a job."""

    job_id: str = Field(..., description="Unique identifier of the job.")
    status: JobStatus = Field(..., description="Initial status of the job.")
    media_type: MediaType = Field(..., description="Type of media detected.")
    filename: str = Field(..., description="Original filename of the file.")
    created_at: datetime = Field(..., description="Timestamp of job creation.")
    poll_url: str = Field(
        ...,
        description="URL to query the status of the job (polling).",
    )


class JobStatusResponse(BaseModel):
    """Response of the status query of a job."""

    job_id: str = Field(..., description="Unique identifier of the job.")
    status: JobStatus = Field(..., description="Status of the job.")
    created_at: datetime = Field(..., description="Timestamp of job creation.")
    updated_at: datetime = Field(..., description="Timestamp of job update.")
    result: AnalysisResult | None = Field(
        default=None,
        description="Analysis result (filled when status=completed).",
    )
    error: str | None = Field(
        default=None,
        description="Error message (filled when status=failed).",
    )


class HealthResponse(BaseModel):
    """Response of the health check endpoint."""

    status: str = Field(..., description="General status of the service.")
    app_name: str
    app_version: str
    model_name: str
    model_loaded: bool = Field(
        ...,
        description="Indicates if the VLM model has been loaded in memory.",
    )
    device: str = Field(..., description="Device where the model is running.")
    cuda_available: bool
    active_jobs: int = Field(..., description="Number of jobs in memory.")


class ErrorResponse(BaseModel):
    """Standard error response."""

    detail: str = Field(..., description="Error message.")
